# Generated by Django 3.2.8 on 2021-11-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
