# Generated by Django 3.2.8 on 2021-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('question', models.CharField(max_length=25)),
                ('choice', models.CharField(max_length=25)),
                ('instruction_time', models.CharField(blank=True, max_length=25)),
                ('quiz1_time', models.CharField(blank=True, max_length=25)),
                ('quiz2_time', models.CharField(blank=True, max_length=25)),
                ('feedback_time', models.CharField(blank=True, max_length=25)),
                ('duration', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
