# Generated by Django 3.2.8 on 2021-11-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0002_auto_20211117_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='choice',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='question',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
