# Generated by Django 3.2.8 on 2021-11-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0003_auto_20211117_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='choice',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
