# Generated by Django 3.2.8 on 2021-11-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0004_auto_20211117_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='user',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
