# Generated by Django 3.2.8 on 2021-11-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0005_alter_pretest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretest',
            name='event',
        ),
    ]
