# Generated by Django 3.2.8 on 2021-11-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0006_remove_pretest_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretest',
            old_name='quiz1_time',
            new_name='quiz1Time',
        ),
    ]
