# Generated by Django 3.2.8 on 2021-11-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0007_rename_quiz1_time_pretest_quiz1time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time_stamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='video_time',
            new_name='videoTime',
        ),
        migrations.RenameField(
            model_name='pretest',
            old_name='feedback_time',
            new_name='feedbackTime',
        ),
        migrations.RenameField(
            model_name='pretest',
            old_name='instruction_time',
            new_name='instructionTime',
        ),
        migrations.RenameField(
            model_name='pretest',
            old_name='num_clicks',
            new_name='numClicks',
        ),
        migrations.RenameField(
            model_name='pretest',
            old_name='quiz2_time',
            new_name='quiz2Time',
        ),
        migrations.RenameField(
            model_name='pretest',
            old_name='time_stamp',
            new_name='timeStamp',
        ),
    ]
