# Generated by Django 3.2.8 on 2021-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0008_auto_20211118_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='timeStamp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
