# Generated by Django 3.2.8 on 2021-11-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0010_vectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='vectorsLog',
        ),
    ]
