# Generated by Django 3.2.8 on 2021-11-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0011_rename_log_vectorslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorslog',
            name='videoNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vectorslog',
            name='user',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
