# Generated by Django 3.2.8 on 2021-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0013_vectors_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorslog',
            name='timeStamp',
            field=models.CharField(max_length=100),
        ),
    ]
