# Generated by Django 3.2.8 on 2021-12-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0015_pretestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='pretestMouseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=25)),
                ('timeStamp', models.CharField(max_length=100)),
                ('mouseX', models.CharField(blank=True, max_length=25)),
                ('mouseY', models.CharField(blank=True, max_length=25)),
                ('clickX', models.CharField(blank=True, max_length=25)),
                ('clickY', models.CharField(blank=True, max_length=25)),
                ('clickedITMtl', models.CharField(blank=True, max_length=25)),
                ('clickedITMbr', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='feedbackTime',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='instructionTime',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='numClicks',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='quiz1Time',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='quiz2Time',
        ),
    ]
