# Generated by Django 3.2.8 on 2021-12-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0019_vectorslog_videonumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorslog',
            name='videoTime',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
