# Generated by Django 3.2.8 on 2022-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0022_posttest_posttestlog_posttestlog2_posttestmouseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcelog',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posttestlog',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posttestlog2',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pretestlog',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pretestlog2',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vectorslog',
            name='event',
            field=models.CharField(max_length=100),
        ),
    ]
