# Generated by Django 3.2.8 on 2022-02-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0023_auto_20220129_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcelog',
            name='Wandering',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorslog',
            name='Wandering',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
