# Generated by Django 3.2.8 on 2022-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0024_auto_20220203_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcelog',
            name='keyPresses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorslog',
            name='keyPressed',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
