# Generated by Django 3.2.8 on 2022-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0026_auto_20220204_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestmouseevent',
            name='keyPressed',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
