# Generated by Django 3.2.8 on 2022-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0027_pretestmouseevent_keypressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcemouseevent',
            name='videoNumber',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='forcemouseevent',
            name='videoTime',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorsmouseevent',
            name='videoNumber',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vectorsmouseevent',
            name='videoTime',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
