# Generated by Django 3.2.8 on 2022-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0029_auto_20220204_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='forceedu',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='forcelog',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='forcemouseevent',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='posttestedu',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='posttestlog',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='posttestmouseevent',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pretestedu',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pretestlog',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pretestmouseevent',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vectorsedu',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vectorslog',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vectorsmouseevent',
            name='pageState',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
