# Generated by Django 3.2.8 on 2022-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0030_auto_20220204_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretestlog',
            old_name='clickX',
            new_name='Wandering',
        ),
        migrations.RenameField(
            model_name='pretestlog',
            old_name='clickY',
            new_name='videoNumber',
        ),
        migrations.AddField(
            model_name='pretestlog',
            name='videoTime',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
