# Generated by Django 3.2.8 on 2022-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Force_HLG', '0031_auto_20220206_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestlog',
            name='user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pretestmouseevent',
            name='user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vectorslog',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
